### ISSUE TITLE
[Feature] [Backoffice] User Area 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#1]
**What**: When any user logs in they should have access to their user area that allows to change password, contact email, contact phone, name.  aka **[Information]** 

**If** the user is the **admin** it should have access to a list of all users and be able to edit the **[Information]** of any user including itself.

**Comment by ricardo-jorge-tavares** [comment]
Users list page for admin is done.

TODO: page for changing personnal information...

**Comment by ricardo-jorge-tavares** [comment]
Done...
