### ISSUE TITLE
[Bug] Errors are not being redirected to an error page 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#10]
**WHAT:** Errors (like the 404 described in https://github.com/vostpt/Api-Open4Business/issues/1) are not being redirected to an error page
**SOLUTION:** Make sure that all errors are redirected to an error page, with the design specs present in the Invision project

**Comment by ricardo-jorge-tavares** [comment]
I believe that the situation is solved, but will keep issue opened until new tests on DEV stage...

**Comment by ricardo-jorge-tavares** [comment]
Solved!
