### ISSUE TITLE
[Bug] [BackOffice] Submission by admin account

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#11]
**WHAT:** Submission of bulk file, by admin account, returns the error 
"Ocorreu um erro ao registar (...) Contacte serviços de apoio"
**REPLICATE:** 
Login with admin account
Goto https://dev-open4biz.vost.pt/businesses/locations/new
Try to submit file
SOLUTION: Make sure that admin account can upload bulk files **and** submission form is working properly

**Comment by baldasman** [comment]
Solved. Please test.
