### ISSUE TITLE
[Bug] Not able to register new company

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#12]
**WHAT:** When trying to create new company the system returns an error message
**REPLICATE**: Go to https://dev-open4biz.vost.pt/auth/signup and try to submit a new company
**SOLUTION**: User should be able to signup with no errors
**ADITIONAL NOTES:** System should check if e-mail / Company already exists and IF it does show message:
**"A sua empresa já se encontra registada. Clique aqui para fazer login"**

**Comment by ricardo-jorge-tavares** [comment]
Solved.
