### ISSUE TITLE
[Backoffice] [Design] Remove template file screenshot

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#13]
**WHAT:** Submission page has a template file screenshot
**REPLICATE:** Go to https://dev-open4biz.vost.pt/businesses/locations/new after login
![Screenshot 2020-04-18 at 13 27 37](https://user-images.githubusercontent.com/34355337/79637560-765bae80-8178-11ea-8fe4-c163087d3df4.png)

**SOLUTION**: Remove screenshot template

**ADITIONAL NOTES:** 
When **the admin accounts logs in**, it should be taken to the administration area, not to the upload file screen.

**Comment by ricardo-jorge-tavares** [comment]
The "Descarregar exemplo do CSV" button remains or is also to remove?

**Comment by JorgeMiguelGomes** [comment]
> The "Descarregar exemplo do CSV" button remains or is also to remove?

Only the image (screenshot of the template) is to be removed

**Comment by JorgeMiguelGomes** [comment]
Remains. Only the image (screenshot of template) is to be removed.

**Comment by ricardo-jorge-tavares** [comment]
Changed as requested...

(will be available on the next deploy)
