### ISSUE TITLE
[Bug] [Signup] Company user e-mail is not being sent to the correct address 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#15]
**WHAT:** When a company signs up, the first confirmation e-mail is not being sent to the specified address. At the moment is being sent to `jorge.gomes@vost.pt`
**REPLICATE:** Create a new company. Confirmation e-mail will not be received on the e-mail that was used to register. 
**SOLUTION:** When a company signs up they should receive a confirmation e-mail, sent to the e-mail that they used on registering. 
This issue goes along with #16

**Comment by baldasman** [comment]
Solved. Please test.
