### ISSUE TITLE
[Bug] [Validation] Account activation  e-mail is not being sent to the correct address 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#16]
**WHAT:** When admin confirms an account the email, informing that the account is now active is being sent to `jorge.gomes@vost.pt ` instead of the e-mail with which the user registered the company. 
**REPLICATE:** Sign up a new company. No e-mail will be received when account is activated. 
**SOLUTION:** Make sure that the activation email is sent to the email used by the user to register the account

This issue goes along with #15

**Comment by baldasman** [comment]
Solved.
