### ISSUE TITLE
[Design] Information Card 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#19]
![Screenshot 2020-04-19 at 17 13 51](https://user-images.githubusercontent.com/34355337/79693214-420fed00-8261-11ea-83ee-b6b882e2f270.png)

1. Make sure that the card ends, horizontally where yellow bar is. 
2. Include `sector`and `parish`in the card

**Comment by baldasman** [comment]
Solved
