### ISSUE TITLE
[Design] [Content] Remove footer item

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#2]
![image](https://user-images.githubusercontent.com/34355337/79597707-ad7b8280-80da-11ea-8eb2-7b322b5b4e54.png)

Please remove footer item and replace with 

**VOSTPT COVID19** Links to: `https://covid19pt.vost.pt target="_blank"` 
Hub de informação sobre a atuação da VOST Portugal durante a pandemia de COVID-19.

**Comment by ricardo-jorge-tavares** [comment]
Executed as requested.
