### ISSUE TITLE
[Feature] [BackOffice] Allow business owners to eliminate duplicate registration

### ISSUE THREAD

**Issue by marcoacmaia** [vostpt/Web-Open4Business#23]
When we have 4 similar entries, we are unable to eliminate this duplicate record.
![mmstore](https://user-images.githubusercontent.com/49103846/79693927-55bd5280-8265-11ea-8f5b-dd3e86952a4b.PNG)

**Comment by JorgeMiguelGomes** [comment]
# GOAL
Allow users to bulk delete entries
Allow users to bulk edit entries
Allow users to edit single submissions
Allow users to delete single submissions

**Comment by baldasman** [comment]
Single edit and delete only
