### ISSUE TITLE
[Design] [Bug] Card not including all information given in CSV file 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#24]
# GOAL
Card must include **all** information given by the user for each entry
# CURRENT
![Screenshot 2020-04-19 at 18 00 37](https://user-images.githubusercontent.com/34355337/79694361-be0d3380-8267-11ea-8d13-c06d496f6efe.png)

This is the card generated from this entry:
/
`JG,JG01 - ALVALADE,Rua da Liberdade,Alvalade,Santiago-do-Cacém,Beja,7565-005,37.940869,-8.391186,999999999,Restauração,07:30-10:30,"segunda,terça,quarta,quinta,sexta",Forças de Segurança e Profissionais de Saúde,Manhã,10:30-12:00,"segunda,terça,quarta,quinta,sexta",Idosos,Manhã,"sábado,domingo",10:00-19:00,Público em Geral,Dia Completo,SIM,999999999,Estafeta Próprio,Entregas gratuitas`
/
As you can see the card cuts the information, doesn't include `tipo de horário`, doesn't include ` Por Marcação`(if **Sim**) and `Contacto Agendamento`(if `Marcação` = Sim)

**Comment by baldasman** [comment]
Solved
