### ISSUE TITLE
[Bug] [Backoffice] Approved Submissions still show up in the review section

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#26]
# WHAT
After a batch submission is approved it should not longer appear in the review section. 
# REPLICATE
Go to https://dev-open4biz.vost.pt/businesses/locations/review 
# GOAL

1. Make sure that there is **a button** for admin to go into the review area
2. Make sure that admin has a **function to review** pending batch submissions
3. List **batch submissions** by batch, not single entries
4. Make sure that admin can approve **single pending** submissions 
5. **EXTRA** Create a notifications' system for admin account

**Comment by baldasman** [comment]
Implemented apart from notifications system for admin account
