### ISSUE TITLE
[Bug] [Map] "Navegar" takes you to a different location on Google Maps

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#27]
# GOAL
When user clicks on the "Navegar" button it should:
- Choose which navigation app to use 
- Be taken to the exact point 

# WHAT

Please look at the image sequence:
_______________________________________
**Store Location with correct address**
![Screenshot 2020-04-22 at 02 27 36](https://user-images.githubusercontent.com/34355337/79961419-99d76f80-847e-11ea-9349-cb0a6f0b90fd.png)

**Store Location in Local Map also correct**
![Screenshot 2020-04-22 at 09 49 36](https://user-images.githubusercontent.com/34355337/79961774-18341180-847f-11ea-82ac-874379f6da8e.png)
_____
**Clicking "Navegar" takes you to a different point, still in the same region, but not exact**
![Screenshot 2020-04-22 at 02 27 09](https://user-images.githubusercontent.com/34355337/79961541-c7241d80-847e-11ea-996b-f7f05cea506d.png)

**Comment by baldasman** [comment]
Solved!
