### ISSUE TITLE
[Bug] Double Menu Behaviour on Mobile

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#3]
![image](https://user-images.githubusercontent.com/34355337/79598053-35fa2300-80db-11ea-990a-d3ad6f947e60.png)

**WHAT:**  On mobile the frontend is showing two different menus. 
**Replicate:** Access via mobile https://dev-open4biz.vost.pt/ 
**Solution:** Make sure that the mobile menu is unique

**Comment by ricardo-jorge-tavares** [comment]
Implemented as requested...
