### ISSUE TITLE
[Design] Mapbox Template

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#4]
![image](https://user-images.githubusercontent.com/34355337/79598374-bf115a00-80db-11ea-8363-71c9ccc087c9.png)

Please use Mapbox template that delineates borders in **red**

**Comment by ricardo-jorge-tavares** [comment]
I believe that this style requires some kind of configuration trough mapbox account (mapbox studio?).

Is it possible that you could investigate this situation? Or could you could provide access?

**Comment by JorgeMiguelGomes** [comment]
> I believe that this style requires some kind of configuration trough mapbox account (mapbox studio?).
> 
> Is it possible that you could investigate this situation? Or could you could provide access?
**This is the style** https://api.mapbox.com/styles/v1/vostpt/ck94io81o3y4k1iqpfzjvz0vu.html?fresh=true&title=copy&access_token=pk.eyJ1Ijoidm9zdHB0IiwiYSI6ImNqeXR3aHQxdTAyYjgzY21wbDMwaHJoaDQifQ.ql-IskzjOdAtEFvbltquaw

Will provide token privately

**Comment by ricardo-jorge-tavares** [comment]
Thanks!
