### ISSUE TITLE
[Design] [Frontend] [Header] Fix logo on mobile

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#6]
![image](https://user-images.githubusercontent.com/34355337/79601985-9c823f80-80e1-11ea-9ed1-8f5653a2a7bd.png)

**WHAT**: Logo is not scaling correctly on mobile 
Replicate: Access website via mobile 
Solution: Make sure logo scales depending on screen resolution

**Comment by ricardo-jorge-tavares** [comment]
Implemented as requested...
