### ISSUE TITLE
[Backoffice] [Content] 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#7]
**WHAT**: When a "Big Company" account log sin, they are taken to the upload screen. The copy on that screen as to be changed to the one already provided. 
**WHERE**: https://dev-open4biz.vost.pt/businesses/locations/new
**SOLUTION**: Change "Lorem Ipsum" by final copy including the link to the template document.

**Comment by ricardo-jorge-tavares** [comment]
Gonna include the template image, but invision page has "lorem ipsum" text. ;)

Can you provide a new text, or pointing me to where it resides?

**Comment by JorgeMiguelGomes** [comment]
> Gonna include the template image, but invision page has "lorem ipsum" text. ;)
> 
> Can you provide a new text, or pointing me to where it resides?

"Nesta área pode fazer o upload em _bulk_ dos dados da sua empresa. Se ainda não o fez, aconselhamos a que primeiro **[leia as instruções de preenchimento](https://bit.ly/O4B_READMEFIRST)** e exportação dos dados no formato correto, e aceite por esta plataforma. O ficheiro template pode ser encontrado **[aqui](bit.ly/VOSTPT_O4B_MS_TEMPLATE)**
Se porventura o ficheiro não for aceite pelo sistema, verifique de novo a sua estrutura e os dados. Se o erro persistir por favor contacte-nos via o4b@vost.pt"

**Comment by ricardo-jorge-tavares** [comment]
Thanks...

Improved as requested...
