### ISSUE TITLE
[Frontend] [Content] Change Copy

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#8]
**WHAT**: Copy that is appearing after registering is the one to be used for single submissions
![Screenshot 2020-04-17 at 19 43 50](https://user-images.githubusercontent.com/34355337/79603269-ec620600-80e3-11ea-92b4-fe645acd64ef.png)
**WHERE**: https://dev-open4biz.vost.pt/auth/signup/success
**SOLUTION**: Change copy to >
"**O seu pedido foi registado com sucesso. Após validação irá receber um e-mail de confirmação, com as sua credenciais**"

**Comment by ricardo-jorge-tavares** [comment]
Change as requested...
