### ISSUE TITLE
[Email] [Content] Admin validation e-mail 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Web-Open4Business#9]
![Screenshot 2020-04-17 at 19 50 29](https://user-images.githubusercontent.com/34355337/79603793-e3256900-80e4-11ea-9e6b-33e63e8caa5d.png)
**WHAT:** Copy on received email can be confusing. 
**SOLUTION:** Change copy to:

**"New Company Registered"**
and
**"Click the link below to confirm new account"**

**Comment by baldasman** [comment]
Solved.
